function toShorten(name, origin){
  return encodeURIComponent(
    name.toLowerCase().split('').reverse().join('')+
    '-'+
    origin.toLowerCase().split('').reverse().join('')
  );
}

function getInviteeFromShorten(shorten){
  return invitation_names.filter(function(invitee){
    return toShorten(invitee.name, invitee.origin) === shorten;
  })[0];
}

// the url format is chenxeed.github.io/albertliana/index.html?o=shorten
function getShortenFromURL(url){
  return url.split('index.html?o=')[1];
}

function getURLFromShorten(shorten){
  return window.location.origin+'/albertliana/index.html?o='+shorten;
}

var invitation_names = [{"name":"Mr Agung S Santosa","subname":"Jakarta","printed":"O","origin":"Binus"},
{"name":"Andre & Family","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Derry & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Alvin & Deasy","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Junaidi Lie & Keluarga","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Rere & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"William & Anitawati","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Romo Heriyadi & Keluarga","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Nizarwan & Nina","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Jimmy & Deasyka","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Sanie & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Rudi Kode & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Leonardo & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Noven & Keluarga","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Hendra & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Alek & Keluarga","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Tedy & Wahyu","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Mikhael & Gisella","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Budi & Sance","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Anggi & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Herman & Family","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Keluarga Ivan & Metta","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Astri Wulandari & Keluarga","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Heriyanto & Selvi","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Yodi & Selva","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Sandi Mekanik & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Hendra Gunawan & Keluarga","subname":"","printed":"X","origin":"Buddhi"},
{"name":"Sandy Santosa & Partner","subname":"","printed":"X","origin":"Buddhi"},
{"name":"Andy & Hanny","subname":"","printed":"X","origin":"Buddhi"},
{"name":"Cinsong","subname":"","printed":"X","origin":"Buddhi"},
{"name":"","subname":"","printed":"","origin":""},
{"name":"Daniel & Family","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Kitti & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Eka & Partner","subname":"","printed":"O","origin":"Buddhi"},
{"name":"Lukman Susilo & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Erwin Kosim","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Ai Susi & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mrs Trisna & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mrs Elly Tanudjaya & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Sukento Supandy & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Andrew Royce D","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Herry Gautama","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Ms Sherly Gautama","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Rudy Gunawan","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mrs Swarna effendi & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Anna mahony & Family","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mrs Meylinda Wijaya & Family","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Elisabeth Bachtiar","subname":"DBS","printed":"X","origin":"DBS"},
{"name":"Mr & Mrs Yeferi sutanto","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs Alexander C Eonardo","subname":"Jakarta","printed":"O","origin":"DBS"},
{"name":"Mrs Narita & Family","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Felly Augusthy & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Winny Chandra","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mrs Wei wei & Family","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mrs Lily suntono & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs Irvan P Djimantoro","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mrs Kartini wijaya & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Ervani","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Lia kusuma","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Husain & Shierly Metta","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Adi O","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs Leonardi Tanril","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Lieta Widya Swastika & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Yuhana Fitria & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Fachrur rozy & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Achmad fadli","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mrs Herlina Fitrianti & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Shanty Meitria","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mellisa H Mondong & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Sri Yati & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Astrid Anarfin & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Margaret Kamil & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Maximillian","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs M Ridho Indoman","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mrs I Gusti A A Santika & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs Eriko","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Tadly Chandra & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Kandar & Felicia","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Amelia & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Rizky Davita & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Dhisca & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Adya Garini","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Wenda Iriani","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"David & Partner","subname":"Manulife","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs Ady Prasetya M","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr & Mrs Hendy","subname":"Jakarta","printed":"O","origin":"DBS"},
{"name":"Nurul Yekti W ","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Christine J A","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Putra & Partner","subname":"Manulife","printed":"O","origin":"DBS"},
{"name":"Trisnawati","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Mr Hengky & Mrs Yenwi","subname":"Jakarta","printed":"X","origin":"Ex DBS"},
{"name":"Ms Indah & Partner","subname":"Jakarta","printed":"O","origin":"Ex DBS"},
{"name":"Fandi & Elmung","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Guntargen Sintra & Keluarga","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Joeaina Xing","subname":"","printed":"O","origin":"Family Papa"},
{"name":"All HEAT Family","subname":"","printed":"X","origin":"HEAT"},
{"name":"Mrs Hua Bie & Family","subname":"Jakarta","printed":"O","origin":"Jakarta"},
{"name":"Ai teng & Kel","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ai sisit ","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ci leli","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ci Lena ","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ko Oklay ","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Mpe Sikim & kel","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ko deny","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Cide","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ci iing","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Oo Ayong","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Epi","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Cek Aik & Kel ","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Cek Aan ","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Cek Ali","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Cek alin","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ode","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Oo wawah","subname":"","printed":"X","origin":"Family Liana"},
{"name":"mertua o ayong","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ipo Tasik","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Ardy & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Siska & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Riswan & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Wulan & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Uchen & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Novylia (Nope) & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Edison & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Hadik & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Rudyanto & Binardewi","subname":"","printed":"X","origin":"KMB"},
{"name":"Agus Prayogo & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Yulisna & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Michael Sam & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Joko & Family","subname":"","printed":"X","origin":"KMB"},
{"name":"Chandra Tole & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Rasmianto Leliga & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Yek Ngo & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Anwar & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Jordan & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Juwita & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Aseng & Apheng","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Ming Lai & Yek Mei","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Rusli Djingga & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Diana Djingga & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Husin Djingga & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Yek Sin & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Asien Akim & Family","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Abby & Linda","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Paimin & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Rico & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Suherman & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Haris WP & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"Leonard Hendra & Yulita","subname":"","printed":"X","origin":"KMBD"},
{"name":"Henry & Vera","subname":"","printed":"X","origin":"KMBD"},
{"name":"Kisman & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Hendri Yauw & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Agus Suhendri & Olivia","subname":"","printed":"X","origin":"KMBD"},
{"name":"Dewi Farida & Family","subname":"","printed":"X","origin":"KMBD"},
{"name":"Effendi Budiman & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Edwin & Noviyanty","subname":"","printed":"X","origin":"KMBD"},
{"name":"Willyanto & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Syung2 & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"So Agung Siddharta & Eli","subname":"","printed":"X","origin":"KMBD"},
{"name":"Emil & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Mario Andika & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Desman Hidayat & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Jansen & Cherry","subname":"","printed":"X","origin":"KMBD"},
{"name":"Peter & Febri","subname":"","printed":"X","origin":"KMBD"},
{"name":"PI KMBD XXIV","subname":"","printed":"X","origin":"KMBD"},
{"name":"PI KMBD XXIII","subname":"","printed":"X","origin":"KMBD"},
{"name":"PI KMBD XXII","subname":"","printed":"X","origin":"KMBD"},
{"name":"Alfred & Serly","subname":"","printed":"X","origin":"KMBD"},
{"name":"Toni Kamaruddin & Wenda","subname":"","printed":"X","origin":"KMBD"},
{"name":"Martin Wijaya & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Harianto  & Dina","subname":"","printed":"X","origin":"KMBD"},
{"name":"Melvin & Juleha","subname":"","printed":"X","origin":"KMBD"},
{"name":"Hendra & Dewi","subname":"","printed":"X","origin":"KMBD"},
{"name":"Harris Kristanto & Tiana","subname":"","printed":"X","origin":"KMBD"},
{"name":"Novandri & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Johanes & Yulieni","subname":"","printed":"X","origin":"KMBD"},
{"name":"Harry & Mimi","subname":"","printed":"X","origin":"KMBD"},
{"name":"Julius Nugraha & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Apriyanti & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Adyanti & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Alfri Susanti & Henry","subname":"","printed":"X","origin":"KMBD"},
{"name":"Ko Jou Liang & Ci Ang Peng Peng","subname":"","printed":"X","origin":"KMBD"},
{"name":"Deny & Dessika","subname":"","printed":"X","origin":"KMBD"},
{"name":"Manise & Family","subname":"","printed":"X","origin":"KMBD"},
{"name":"Julius Purwanto & Kartika","subname":"","printed":"X","origin":"KMBD"},
{"name":"Fenny & Guntoro","subname":"","printed":"X","origin":"KMBD"},
{"name":"Andi Juanda & Family","subname":"","printed":"X","origin":"KMBD"},
{"name":"Samcek & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Anthony Xie & Yulie","subname":"","printed":"X","origin":"KMBD"},
{"name":"Intan & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Metta Mini & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Rina & Nico","subname":"","printed":"X","origin":"KMBD"},
{"name":"Dewi Octavia & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Donna Adriani & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Sherly & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Suryanto & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Johanes & Yulieni","subname":"","printed":"X","origin":"KMBD"},
{"name":"Ramli & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Adhi Lukman & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Harry Leo & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Effendi Rijono & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Chandra Huang & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Erli Lee & Susi","subname":"","printed":"X","origin":"KMBD"},
{"name":"PI KMBD XXI","subname":"","printed":"X","origin":"KMBD"},
{"name":"Fendi Kartono & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Desy, Afang, Jenny & Ricky w/ Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Megawati & Partner","subname":"","printed":"X","origin":"KMBD"},
{"name":"Cicilia J T (Cello) & Partner","subname":"","printed":"X","origin":"KMB"},
{"name":"KMBD XX","subname":"","printed":"X","origin":"KMBD"},
{"name":"Hungkwo & Mely","subname":"","printed":"X","origin":"KMBD"},
{"name":"Mr & Mrs Harryanda Gunawan","subname":"Jakarta","printed":"O","origin":"Lampung"},
{"name":"Erwin Wijaya & Partner","subname":"Jakarta","printed":"O","origin":"Lampung"},
{"name":"Meydi Lie & Partner","subname":"Jakarta","printed":"O","origin":"Lampung"},
{"name":"Mrs Yiping & Partner","subname":"Jakarta","printed":"O","origin":"Lampung"},
{"name":"Papa Mama","subname":"","printed":"O","origin":"Family Liana"},
{"name":"Koko","subname":"","printed":"O","origin":"Family Liana"},
{"name":"Rita & Gerry","subname":"","printed":"O","origin":"Family Liana"},
{"name":"Encen & Fam","subname":"","printed":"O","origin":"Family Liana"},
{"name":"Kuku & akim","subname":"","printed":"O","origin":"Family Liana"},
{"name":"Papa & mama soso","subname":"","printed":"O","origin":"Family Liana"},
{"name":"Mpe Ayong","subname":"","printed":"X","origin":"Family Liana"},
{"name":"mpe isin","subname":"","printed":"X","origin":"Family Liana"},
{"name":" ii anyo","subname":"","printed":"X","origin":"Family Liana"},
{"name":"ko yayang","subname":"","printed":"X","origin":"Family Liana"},
{"name":"ko aming","subname":"","printed":"X","origin":"Family Liana"},
{"name":"ko Acong","subname":"","printed":"X","origin":"Family Liana"},
{"name":"ko kaciu","subname":"","printed":"X","origin":"Family Liana"},
{"name":"Om Kotu","subname":"","printed":"X","origin":"Family Liana"},
{"name":"MAIZEN","subname":"","printed":"X","origin":"MicroAd"},
{"name":"Willyam Surya & Partner","subname":"","printed":"X","origin":"PI XX"},
{"name":"Teguh Budiman & Partner","subname":"","printed":"X","origin":"PI XX"},
{"name":"Kristle & Partner","subname":"","printed":"X","origin":"PI XX"},
{"name":"Evelyn & Partner","subname":"","printed":"X","origin":"PI XX"},
{"name":"Hendri Trestiawan & Margaret","subname":"","printed":"X","origin":"PI XX"},
{"name":"Jeffry Chen & Partner","subname":"","printed":"X","origin":"PI XX"},
{"name":"Erin Vivi & Partner","subname":"","printed":"X","origin":"PI XX"},
{"name":"Iman & Hanny","subname":"","printed":"X","origin":"PI XX"},
{"name":"Mr & Mrs Robert Suparto","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mr Teguh Bagja Saputra & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mr Stephen Natanael K & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mr Kenney Kurniawan & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mr Sulivan & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mrs Kartika Hutapea & Partner ","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Irma Murwanti & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mrs Monika Laurensia & Partner","subname":"Jakarta","printed":"X","origin":"RMDP"},
{"name":"Fitri Angela Tobing & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mr & Mrs Handry Yovan","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mrs Yuniarti & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Febriyanto & Partner","subname":"Jakarta","printed":"O","origin":"RMDP"},
{"name":"Mrs Ana & Partner","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mrs Ningsih & Partner","subname":"Jakarta","printed":"X","origin":"SCB"},
{"name":"Mrs Ayu & Partner","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Ms Agnes & Partner","subname":"Jakarta","printed":"X","origin":"SCB"},
{"name":"Gloria Djoharsjah & Partner","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mrs Sabrina & Partner","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Hencen Tantono & Partner","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mr Hartono Budiarto","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Christian & Marilyn","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mrs Lydia Floren & Family","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mrs Lusy Darmawan & Family","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mrs Stephanie Chandra & Family","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mr & Mrs Ricky","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mr & Mrs Christian Anugraha","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Mr & Mrs Johny Harkinto","subname":"Jakarta","printed":"O","origin":"SCB"},
{"name":"Donny Permana & Partner","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Denny Howman & Partner","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Pingkan & Partner","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Juliarto & Brenda","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Steve & Susan","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Aman Suhe & Partner","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Santo & Partner","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Thomas & Family","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Billi & Partner","subname":"","printed":"X","origin":"Stamanara"},
{"name":"Kuku Eddy","subname":"Tangerang","printed":"O","origin":"Family Liana"},
{"name":"Mr Lie Kin Siong & Family","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Mr Shi Leng Lie & Family","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Mr Dicky Kusumohardjo","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Pdt Romo Gouw Tjeng Sun","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Romo Ahwa","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Y.M Bhikkhu Vihara Hemadhiro Mettavati","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Bowo","subname":"Jakarta","printed":"X","origin":"VHM"},
{"name":"ii sasa","subname":"Jakarta","printed":"X","origin":"VHM"},
{"name":"Mama Sasa","subname":"Jakarta","printed":"X","origin":"VHM"},
{"name":"Mr & Mrs Indra Kurniawan","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Sasa","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Amelia & Partner","subname":"DBS","printed":"O","origin":"DBS"},
{"name":"Yulia Fransisca Ompi & Partner","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Anita Lestari & Partner","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Mrs Bella Wahidi & Family","subname":"Jakarta","printed":"O","origin":"VHM"},
{"name":"Adesui & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Erwin Sintra & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Hermanto Asiong & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Juwita Min2 & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Cin2 & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Lili Hera & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Awie & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Abo & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Hussain & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Abdul Hasan & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Dohley Sintra & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Lijana & Family","subname":"","printed":"O","origin":"Family Papa"},
{"name":"Stephanie & Family","subname":"","printed":"X","origin":"Binus"},
{"name":"Frans & Meiling","subname":"","printed":"X","origin":"Binus"},
{"name":"Fernando Halim & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Harry Setiawan & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Frans Yosua & Family","subname":"","printed":"X","origin":"Binus"},
{"name":"Agung Putuwinata & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Steeven & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Handy Gusman & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Wilson Chandra & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Hendry & Retha","subname":"","printed":"X","origin":"Binus"},
{"name":"Chris ","subname":"","printed":"X","origin":"Binus"},
{"name":"Andreas & Wulan","subname":"","printed":"X","origin":"Binus"},
{"name":"Eunike Yuliana & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Hendra ","subname":"","printed":"X","origin":"Binus"},
{"name":"Fendy Willyam & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Michael Wijaya & Juli","subname":"","printed":"X","origin":"Binus"},
{"name":"Tomy Wirawan & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Yusna Wang & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Fredy Leonheart & Partner","subname":"","printed":"X","origin":"Binus"},
{"name":"Eric & Steffie","subname":"","printed":"X","origin":"Laguna"},
{"name":"Marco & Partner","subname":"","printed":"X","origin":"Laguna"},
{"name":"Elvis & Partner","subname":"","printed":"X","origin":"Laguna"},
{"name":"Erick Dubs & Partner","subname":"","printed":"X","origin":"Laguna"},
{"name":"Sian Chung & Family","subname":"","printed":"X","origin":"Laguna"},
{"name":"Bambang ","subname":"","printed":"X","origin":"Laguna"},
{"name":"Rody & Partner","subname":"","printed":"X","origin":"Laguna"},
{"name":"Rosen & Partner","subname":"","printed":"X","origin":"Laguna"},
{"name":"James Djapri & Partner","subname":"","printed":"X","origin":"Laguna"},
{"name":"Elisa Yoshigue & Partner","subname":"","printed":"X","origin":"MicroAd"},
{"name":"Yoshiki Enohara & Family","subname":"","printed":"X","origin":"MicroAd"},
{"name":"Steven Sumin & Family","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Nofanto & Windy","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Santoso Nugroho & Family","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Nugroho Sigit & Family","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Albar Farisi & Family","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Jufri Fan & Family","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Joko & Partner","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Joni & Family","subname":"","printed":"X","origin":"Infoflow"},
{"name":"Melani Sugiharto & Keluarga","subname":"","printed":"X","origin":"Infoflow"},
{"name":"PI KMBD XXV","subname":"KMBD","printed":"X","origin":"KMBD"},
{"name":"Acho & Lili","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Cin2 & Hong2","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Cim Phiao & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Po Giok & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Joko & Poyen","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Po San & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Sulung & Keluarga","subname":"","printed":"O","origin":"Family Mama"},
{"name":"Yuliana & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Yeni & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Imam Syahputra & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Sui Cu & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Sui Siang & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Susan & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Thien Chai & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Chui Ling & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Pai Lan & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Siang Lan & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Mei Lan & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Yek Eh & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Cong Peng & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Wie Ching & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ahi & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Yen Li & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ayek & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Yen San & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ahuat & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Chiu Li & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ito & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Eki & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Pau Yen & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ahau & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Yek Mei & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Xiao Ling & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Xiao Hui & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Li Cin & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Li Li & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Acin Steven & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Atho & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Aai & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ik Thang & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ik Min & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ik Ling & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Po Huat & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Atak & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ce Wie & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ai Cen & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Joni & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Pipi & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Si Ling & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Sui Sien & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Li Chin & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Se In & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Yek Sien & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Kok Sen & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Aluk & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Rika & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Sumi & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Empi & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Elly & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Ami & Keluarga","subname":"","printed":"O","origin":"Teman Mama"},
{"name":"Andy & Nathalia Widjaya","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Eddy & Novita","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Yunny Widjaya & Partner","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Susi Sugianto & Muliaty","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Mimi & Partner","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Handoko & Kumala Dewi","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Helen Sapralingga & Keluarga","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Luvita & Keluarga","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Maderani & Keluarga","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Felicia & Partner","subname":"","printed":"O","origin":"Teman Dollis"},
{"name":"Wilyana dan Olivia","subname":"","printed":"O","origin":"Teman Ci2"},
{"name":"Anita dan Team CConcept","subname":"","printed":"O","origin":"Teman Ci2"},
{"name":"Farinia dan Team Hunter","subname":"","printed":"O","origin":"Teman Ci2"},
{"name":"Dr Kristanto Sulistio & Family","subname":"Jakarta","printed":"X","origin":"Customer"},
{"name":"Sie Siok Kiang","subname":"Jakarta","printed":"X","origin":"Customer"},
{"name":"Ms Lida Tanudjaja","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Hendri","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Bpk Dahlan Gunawan","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Soemarto","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr & Mrs Hengky","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mr Ir Jubianto & Mrs Shirley C","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Bong Christie","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Rismalinda Novita & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Mrs Koeswati Kusman & Family","subname":"Jakarta","printed":"O","origin":"Customer"},
{"name":"Teman2 Ko2","subname":"","printed":"O","origin":"Teman Ko2"},
{"name":"Pak Heru","subname":"","printed":"X","origin":"DLL"},
{"name":"Ayin","subname":"","printed":"X","origin":"DLL"},
{"name":"Teman2 Rita","subname":"","printed":"O","origin":"Teman Rita"},
{"name":"Putra","subname":"","printed":"X","origin":"DLL"},
{"name":"Bapak Kost","subname":"","printed":"X","origin":"DLL"},
{"name":"Desy Fransiska","subname":"Jakarta","printed":"X","origin":"DLL"},
{"name":"Erine Christy","subname":"Lampung","printed":"X","origin":"Lampung"}];